Globs:
  - spec/**/*.cr
  - src/**/*.cr

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/SpecFilename:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/VerboseBlock:
  Enabled: false
