name: QA

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  qa:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.20.2
    steps:
      - uses: actions/checkout@v4
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Build ameba
        run: crystal build lib/ameba/bin/ameba.cr -o bin/ameba
      - name: Run crystal format tool
        run: crystal tool format --check
      - name: Run ameba
        run: ./bin/ameba
